### ISSUE TITLE
How To Create an Admin User

### ISSUE THREAD

**Issue by kwmc-lucas** [mikaeljorhult/hydrofon#98]
Hey @mikaeljorhult, congratulations on this project, it looks fantastic.

I hadn't heard of Laravel and so have spent the evening researching how to get this up and running... it took a while, but I have something! It connects with a MySQL database (at least for users) and runs a PHP Server on Ubuntu.

<img width="1440" alt="Screenshot 2022-01-31 at 23 32 03" src="https://user-images.githubusercontent.com/58596877/151890308-eefa526a-a349-499b-a2d6-b77575250268.png">

I can only see my User and the Book tab, which is greatly reduced from your [screenshot](https://github.com/mikaeljorhult/hydrofon/issues/45#issuecomment-543611406). Is this a database issue, or just what a non-admin would see?

If it's the latter, how do I create an admin account, so that I can start adding Resources?

**Comment by mikaeljorhult** [comment]
Hi Lucas! Thank you, it's a work-in-progress but getting there. =)

You are correct in that it is what a non-admin user would see.

The initial admin user can be created by using the UsersTableSeeder which will create a user with the credentials `default@hydrofon.se` and `default`.

However, since you already have a user you can just go into the database and set the column `is_admin` to `1` and you will be good to go.

**Comment by kwmc-lucas** [comment]
Thanks very much!
